/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a complexAdaptor com.cana.complex.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef COMPLEXADAPTOR_H
#define COMPLEXADAPTOR_H

#include "customdata.h"
#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template <class T> class QList;
template <class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.cana.complex
 */
class ComplexAdaptor : public QDBusAbstractAdaptor {
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.cana.complex")
    Q_CLASSINFO("D-Bus Introspection",
                ""
                "  <interface name=\"com.cana.complex\">\n"
                "    <method name=\"quit\"/>\n"
                "    <method name=\"getString\">\n"
                "      <arg direction=\"out\" type=\"s\"/>\n"
                "    </method>\n"
                "    <method name=\"setString\">\n"
                "      <arg direction=\"in\" type=\"s\" name=\"str\"/>\n"
                "    </method>\n"
                "    <method name=\"setStringList\">\n"
                "      <arg direction=\"in\" type=\"as\" name=\"list\"/>\n"
                "    </method>\n"
                "    <method name=\"getStringList\">\n"
                "      <arg direction=\"out\" type=\"as\"/>\n"
                "    </method>\n"
                "    <method name=\"getCustomData\">\n"
                "      <arg direction=\"out\" type=\"a{sv}\"/>\n"
                "      <annotation value=\"customData\" "
                "name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
                "    </method>\n"
                "    <method name=\"getCustomDataList\">\n"
                "      <arg direction=\"out\" type=\"av\"/>\n"
                "    </method>\n"
                "    <method name=\"getListOfMaps\">\n"
                "      <arg direction=\"out\" type=\"a{sv}\"/>\n"
                "      <annotation value=\"QVariantMap\" "
                "name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
                "    </method>\n"
                "  </interface>\n"
                "")
  public:
    ComplexAdaptor(QObject *parent);
    virtual ~ComplexAdaptor();

  public:         // PROPERTIES
  public Q_SLOTS: // METHODS
    customData getCustomData();
    QList<customData> getCustomDataList();
    QVariantList getListOfMaps();
    QString getString();
    QStringList getStringList();
    void quit();
    void setString(const QString &str);
    void setStringList(const QStringList &list);
  Q_SIGNALS: // SIGNALS
};

#endif
